In [1]:
import pandas as pd

In [5]:
nsl_kdd_df = pd.read_csv("clean_kdd_test.csv")

In [7]:
nsl_kdd_df.columns

Index(['duration', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment',
       'urgent', 'num_failed_logins', 'logged_in', 'root_shell',
       'su_attempted',
       ...
       'flag_REJ', 'flag_RSTO', 'flag_RSTOS0', 'flag_RSTR', 'flag_S0',
       'flag_S1', 'flag_S2', 'flag_S3', 'flag_SF', 'flag_SH'],
      dtype='object', length=112)

In [25]:
nsl_kdd_df.drop(labels = ["attack_binary"], axis = 1, inplace = True)

In [27]:
random_rows = nsl_kdd_df.sample(n=10, random_state=42)

In [29]:
random_rows

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,num_failed_logins,logged_in,root_shell,su_attempted,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
15754,-0.110249,-0.007724,-0.002467,-0.014089,-0.089486,-0.007736,-0.027023,1.235694,-0.036652,-0.024437,...,-0.312889,-0.11205,-0.028606,-0.139982,-0.618438,-0.053906,-0.031767,-0.019726,0.825150,-0.046432
13715,-0.110249,-0.007711,-0.004248,-0.014089,-0.089486,-0.007736,-0.027023,1.235694,-0.036652,-0.024437,...,-0.312889,-0.11205,-0.028606,-0.139982,-0.618438,-0.053906,-0.031767,-0.019726,0.825150,-0.046432
11887,-0.065711,-0.007724,-0.004858,-0.014089,-0.089486,-0.007736,-0.027023,1.235694,-0.036652,-0.024437,...,-0.312889,-0.11205,-0.028606,-0.139982,-0.618438,-0.053906,-0.031767,-0.019726,0.825150,-0.046432
15949,-0.110249,-0.007762,-0.004919,-0.014089,-0.089486,-0.007736,-0.027023,-0.809262,-0.036652,-0.024437,...,-0.312889,-0.11205,-0.028606,-0.139982,1.616978,-0.053906,-0.031767,-0.019726,-1.211901,-0.046432
17765,-0.110249,-0.007756,-0.004919,-0.014089,-0.089486,-0.007736,-0.027023,-0.809262,-0.036652,-0.024437,...,-0.312889,-0.11205,-0.028606,-0.139982,-0.618438,-0.053906,-0.031767,-0.019726,0.825150,-0.046432
10030,-0.108713,-0.005766,-0.004556,-0.014089,-0.089486,-0.007736,-0.027023,1.235694,-0.036652,-0.024437,...,-0.312889,-0.11205,-0.028606,-0.139982,-0.618438,-0.053906,-0.031767,-0.019726,0.825150,-0.046432
17512,-0.110249,-0.007757,-0.004919,-0.014089,-0.089486,-0.007736,-0.027023,-0.809262,-0.036652,-0.024437,...,-0.312889,-0.11205,-0.028606,-0.139982,-0.618438,-0.053906,-0.031767,-0.019726,0.825150,-0.046432
20326,-0.110249,-0.007762,-0.004919,-0.014089,-0.089486,-0.007736,-0.027023,-0.809262,-0.036652,-0.024437,...,-0.312889,-0.11205,-0.028606,-0.139982,1.616978,-0.053906,-0.031767,-0.019726,-1.211901,-0.046432
20617,-0.110249,-0.007723,-0.004056,-0.014089,-0.089486,-0.007736,-0.027023,1.235694,-0.036652,-0.024437,...,-0.312889,-0.11205,-0.028606,-0.139982,-0.618438,-0.053906,-0.031767,-0.019726,0.825150,-0.046432
15113,-0.110249,-0.007755,-0.004880,-0.014089,-0.089486,-0.007736,-0.027023,-0.809262,-0.036652,-0.024437,...,-0.312889,-0.11205,-0.028606,-0.139982,-0.618438,-0.053906,-0.031767,-0.019726,0.825150,-0.046432

In [ ]:
random_rows.to_csv("sample_test_cicids.csv",index=False)

In [9]:
cicids_df = pd.read_csv("clean_cicids_test.csv")

In [11]:
cicids_df.columns

Index(['Destination Port', 'Flow Duration', 'Total Fwd Packets',
       'Total Backward Packets', 'Total Length of Fwd Packets',
       'Total Length of Bwd Packets', 'Fwd Packet Length Max',
       'Fwd Packet Length Min', 'Fwd Packet Length Mean',
       'Fwd Packet Length Std', 'Bwd Packet Length Max',
       'Bwd Packet Length Min', 'Bwd Packet Length Std', 'Flow Bytes/s',
       'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max',
       'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std',
       'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std',
       'Bwd IAT Max', 'Bwd IAT Min', 'Fwd Header Length', 'Bwd Header Length',
       'Fwd Packets/s', 'Bwd Packets/s', 'Min Packet Length',
       'Max Packet Length', 'Packet Length Mean', 'Packet Length Std',
       'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count',
       'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count', 'Down/Up Ratio',
       'Average Packet Size', 'Avg Bwd Segment Size', 'Init_Win_bytes_forward',
       'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward',
       'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean',
       'Idle Std', 'Idle Max', 'Idle Min', 'Label', 'Source_day',
       'attack_binary'],
      dtype='object')

In [17]:
cicids_df.drop(labels=['attack_binary'],axis=1,inplace=True)

In [19]:
random_rows_df = cicids_df.sample(n=10, random_state=42)

In [21]:
random_rows_df

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Source_day
302097,46390,1901,3,1,31,6,31,0,10.333333,17.897858,...,0.0000,0.0000,0,0,0.0,0.000000,0,0,BENIGN,wednesday_df
388527,53,50952,4,2,144,146,36,36,36.000000,0.000000,...,0.0000,0.0000,0,0,0.0,0.000000,0,0,BENIGN,thu_afternoon_df
120220,80,112069927,17,14,442,1774,430,0,26.000000,104.109318,...,117533.8182,302648.3679,1029753,22942,10000000.0,4556.787255,10000000,9993728,BENIGN,tuesday_df
460249,49158,25,1,1,0,6,0,0,0.000000,0.000000,...,0.0000,0.0000,0,0,0.0,0.000000,0,0,PortScan,fri_afternoon_df
239431,53,283,2,2,74,462,37,37,37.000000,0.000000,...,0.0000,0.0000,0,0,0.0,0.000000,0,0,BENIGN,wednesday_df
122926,137,2999250,3,0,150,0,50,50,50.000000,0.000000,...,0.0000,0.0000,0,0,0.0,0.000000,0,0,BENIGN,tuesday_df
447676,1046,46,1,1,0,6,0,0,0.000000,0.000000,...,0.0000,0.0000,0,0,0.0,0.000000,0,0,PortScan,fri_afternoon_df
465375,14442,51,1,1,0,6,0,0,0.000000,0.000000,...,0.0000,0.0000,0,0,0.0,0.000000,0,0,PortScan,fri_afternoon_df
327277,53,228,2,2,58,166,29,29,29.000000,0.000000,...,0.0000,0.0000,0,0,0.0,0.000000,0,0,BENIGN,thu_morning_df
393896,465,1807455,19,23,1413,4520,362,0,74.368421,85.697926,...,0.0000,0.0000,0,0,0.0,0.000000,0,0,BENIGN,fri_morning_df

In [23]:
random_rows_df.to_csv("sample_test_cicids.csv",index=False)